<a href="https://colab.research.google.com/github/Yubinex/pytorch-deep-learning-course/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [10]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()`

In [11]:
# scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [12]:
scalar.ndim

0

In [13]:
# get tensor back as python int
scalar.item()

7

In [14]:
# vector
vector = torch.tensor([7, 7])
print(vector)

tensor([7, 7])


In [15]:
vector.ndim

1

In [16]:
vector.size()

torch.Size([2])

In [17]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX)

tensor([[ 7,  8],
        [ 9, 10]])


In [18]:
MATRIX.ndim

2

In [19]:
MATRIX[0]

tensor([7, 8])

In [20]:
print(MATRIX.shape)

torch.Size([2, 2])


In [21]:
MATRIX.size()

torch.Size([2, 2])

In [22]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
print(TENSOR)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [23]:
TENSOR.ndim

3

In [24]:
print(TENSOR[0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [25]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
print(random_tensor)

tensor([[0.9249, 0.7451, 0.0865, 0.4701],
        [0.3085, 0.1187, 0.1370, 0.8426],
        [0.8361, 0.6545, 0.8289, 0.7924]])


In [26]:
random_tensor.ndim

2

In [27]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [28]:
# create a tensor of all zeros
zero = torch.zeros(size=(3, 4))
print(zero)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [29]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### creating a range of tensors and tensor-like

In [30]:
# use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
print(one_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [31]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [32]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track
                                                    # gradients with this tensor's operations
print(float_32_tensor)

tensor([3., 6., 9.])


In [33]:
float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor)

tensor([3., 6., 9.], dtype=torch.float16)


### Getting information from tensors - Tensor Attributes

1. Tensors not right datatype - to get datatype of a tensor, use `tensor.dtype`
2. Tensors not right shape - to get shape of a tensor, use `tensor.shape`
3. Tensors not on the right device - to get device of a tensor, use `tensor.device`

In [34]:
# create a tensor
some_tensor = torch.rand(3, 4)

In [35]:
# find out detauls about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor:    {some_tensor.shape}")
print(f"Device of tensor:   {some_tensor.device}")

tensor([[0.0492, 0.2486, 0.9138, 0.7303],
        [0.1368, 0.2440, 0.8453, 0.1773],
        [0.7118, 0.2819, 0.7285, 0.3378]])
Datatype of tensor: torch.float32
Shape of tensor:    torch.Size([3, 4])
Device of tensor:   cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [36]:
# create a tensor
# addition
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)

tensor([11, 12, 13])


In [37]:
# subtraction
print(tensor - 10)

tensor([-9, -8, -7])


In [38]:
# multiplication
print(tensor * 10)

tensor([10, 20, 30])


In [39]:
# division
print(tensor / 10)

tensor([0.1000, 0.2000, 0.3000])


In [40]:
# try out pytorch in-built functions
res1 = torch.mul(tensor, 10)
res2 = torch.add(tensor, 10)
res1, res2

(tensor([10, 20, 30]), tensor([11, 12, 13]))

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` - won't work
* `(2, 3) @ (3, 2)` - will work
* `(3, 2) @ (2, 3)` - will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`


In [41]:
# element-wise multiplication
print(f"{tensor} * {tensor} = {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [42]:
# matrix multiplication
print(f"{tensor} @ {tensor} = {tensor @ tensor}")

tensor([1, 2, 3]) @ tensor([1, 2, 3]) = 14


In [43]:
# matrix multiplication by hand
print(1*1 + 2*2 + 3*3)

14


In [44]:
%%time
value = 0
for i in range(len(tensor)): value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.01 ms, sys: 0 ns, total: 2.01 ms
Wall time: 2.02 ms


In [45]:
%%time
torch.matmul(tensor, tensor)

# !! PyTorch functions are very optimized !!

CPU times: user 39 µs, sys: 3 µs, total: 42 µs
Wall time: 57.5 µs


tensor(14)

### One of the most common errors in deep learning: **shape errors**

In [46]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# torch.mm(tensor_A, tensor_B) # -> tensor.mm is the same as torch.matmul, it is an alias
# torch.matmul(tensor_A, tensor_B)
# BOTH WON'T WORK

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.
A **transpose** switches the axes or dimensions of a given tensor.

In [47]:
print(tensor_B, tensor_B.shape)

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]]) torch.Size([3, 2])


In [48]:
print(tensor_B.T, tensor_B.T.shape)

tensor([[ 7,  8,  9],
        [10, 11, 12]]) torch.Size([2, 3])


In [49]:
# the matrix multiplication works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape}")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3])
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [50]:
# create a tensor
x = torch.arange(0, 100, 10)
print(x)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [51]:
# finding the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [52]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [53]:
# find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [54]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [55]:
# find the position in tensor that has the minimum value with argmin
# -> returns index position of target tensor where the minimum value occurs
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [56]:
# find the position in tensor that has the maximum value with argmax
# -> returns index position of target tensor where the maximum value occurs
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of a certain shape but keep the same memory of the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [57]:
# let's create a tensor
import torch
x = torch.arange(1., 10.)
print(x, x.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])


In [58]:
# add an extra dimension
x_reshaped = x.reshape(1, 9)
print(x_reshaped, x_reshaped.shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


In [59]:
# change the view
z = x.view(1, 9)
print(z, z.shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


In [60]:
# changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
print(z, x)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [61]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
print(x_stacked)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])


In [62]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [63]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [64]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [65]:
x_original[0, 0, 0] = 42
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(42.), tensor(42.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumpPy

In [66]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [67]:
# indexing on tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [68]:
# indexing on middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [69]:
# indexing on third bracket (dim=2)
x[0][0][0]

tensor(1)

In [70]:
# you can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [71]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [72]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [73]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [74]:
# get number 9
x[0][2][2], x[0][-1][-1]

(tensor(9), tensor(9))

In [75]:
# index on x to return 3, 6, 9
x[0, :, -1]

tensor([3, 6, 9])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of thos, PyTorch has functionality to interact with it.

* Data in NumPy -> to PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> to NumPy -> `torch.Tensor.numpy()`

In [76]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default dtype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [77]:
# change the value of array, what will this to do `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [78]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [79]:
# change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them a better representation of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.
Essentially what the random seed does is "flavor" the randomness.

In [80]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[3.4285e-04, 3.4274e-01, 2.2587e-01, 7.7717e-01],
        [6.5719e-01, 5.9150e-02, 1.0113e-01, 4.9946e-01],
        [8.1311e-01, 2.5092e-01, 4.9514e-01, 5.6134e-01]])
tensor([[0.0611, 0.1540, 0.6251, 0.7091],
        [0.5381, 0.4104, 0.8029, 0.7206],
        [0.6125, 0.5339, 0.5984, 0.4179]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [81]:
# let's make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Runnding tensors and PyTorch objects on GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything okidoki.

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU
3. Use cloud computing - GCP, AWS, Azure. These services allow you to rent computers on the cloud and access them.

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [82]:
!nvidia-smi

Thu Mar  7 23:39:22 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P0              26W /  70W |    105MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [83]:
import torch
torch.cuda.is_available()

True

In [84]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [85]:
# count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [86]:
# create a tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [87]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu)

tensor([1, 2, 3], device='cuda:0')


### 4. Moving tensors back to the CPU

In [88]:
# if tensor is on GPU, can't transform it to NumPy
# tensor_on_gpu.numpy() # -> results in an error!

In [89]:
# to fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
print(tensor_back_on_cpu)

[1 2 3]
